controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_message_send:
    path:       /message/send
    controller: App\Controller\MessageController::send
    methods:    POST